# CustomMobs Configuration file
# github: https://github.com/FlamingH0rse/CustomMobs
# For more information regarding yml check https://learnxinyminutes.com/docs/yaml/
# General Plugin Settings will be here
settings:
  enable-natural-spawning: false

# # # # # # # # # # # # # # # # # # # # # # # # # # # # # # # # # # # # # # # # # # # # # # # # # # # # # # # # # # # # # # # # # # # # # # # # # # #
# This is where you will place mobs. Here is an example of a mob in it:
#
#  my-super-mob:                     #   This can be in any name. This is the internal name of the mob and it is required
#    display_name: "SuperMob"        #   This is the name displayed to others (like nametag) it also supports color codes
#    type: "Zombie"                  #   The type of the mob (E.g Zombie, Spider etc) For more info regarding supported mobs check the github page
#    stats:                          #   The mobs stats (Specify null for default value)
#      health: 20                    #
#      damage: null                  #
#      speed: null                   #
#                                    #
#    inventory:                      #   Inventory of the mob this is where you can specify what the mob wears for example:
#      main-hand:                    #   Sword Here
#      left-hand:                    #   shield or sword
#      head:                         #   Helmets
#      body:                         #   Chestplates
#      legs:                         #   Leggings
#      foot:                         #   Boots
#                                    #   NOTE: Some mobs do not support armor or holding items such as blaze
#    properties:                     #   General mob properties
#      drops:                        #
#        -                           #
#      spawns-in:                    #
#        enabled: false              #
#        interval:                   #   Spawn mob in each specified tick interval for instance 1000 a mob
#        amount-range:               #   will spawn with the given range in tick in every 1000 tick
#          min:                      #   the min num of mobs that will spawn
#          max:                      #
#        max: 50                     #
#        location:                   #
#          pos-1:                    #   Set 2 position that the mobs will spawn in. Position works similarly just like
#            x:                      #   in worldedit
#            y:                      #
#            z:                      #
#          pos-2:                    #
#            x:                      #
#            y:                      #
#            z:                      #
#
# NOTE: mobs should be placed inside the mobs key
# For more information regarding yml check https://learnxinyminutes.com/docs/yaml/
#
# # # # # # # # # # # # # # # # # # # # # # # # # # # # # # # # # # # # # # # # # # # # # # # # # # # # # # # # # # # # # # # # # # # # # # # # # # #
mobs:
  sample-mob:
    display_name: "&7&lCustom&a&lMob"
    type: "Zombie"
    stats:
      health: 20
      damage: null
      speed: null

    inventory:
      main-hand:
      left-hand:
      head:
        LEATHER_HELMET: "{display:{color:3949738}}"
      body:
        LEATHER_CHESTPLATE: "{display:{color:3949738}}"
      legs:
        LEATHER_LEGGINGS: "{display:{color:3949738}}"
      foot:
        LEATHER_BOOTS: "{display:{color:3949738}}"

    properties:
      drops: null
      spawns-in:
        enabled: false
        interval:
        amount-range:
          min: 2
          max: 5
        max: 50
        location:
          pos-1:
            x:
            y:
            z:
          pos-2:
            x:
            y:
            z: