# CustomMobs Configuration file
# github: https://github.com/FlamingH0rse/CustomMobs
# For more information regarding yml check https://learnxinyminutes.com/docs/yaml/
# General Plugin Settings will be here
settings:
  enable-natural-spawning: false

# # # # # # # # # # # # # # # # # # # # # # # # # # # # # # # # # # # # # # # # # # # # # # # # # # # # # # # # # # # # # # # # # # # # # # # # # # #
# This is where you will place mobs. Here is an example of a mob in it:
#
#  my-super-mob:                     #   This can be in any name. This is the internal name of the mob and it is required
#    display_name: "SuperMob"        #   This is the name displayed to others (like nametag) it also supports color codes
#    type: "Zombie"                  #   The type of the mob (E.g Zombie, Spider etc) For more info regarding supported mobs check the github page
#    stats:                          #   The mobs stats (Specify null for default value)
#      health: 20                    #
#      damage: null                  #
#      speed: null                   #
#                                    #
#    inventory:                      #   Inventory of the mob this is where you can specify what the mob wears for example:
#      main-hand:                    #   Sword Here
#      left-hand:                    #   shield or sword
#      head:                         #   Helmets
#      body:                         #   Chestplates
#      legs:                         #   Leggings
#      foot:                         #   Boots
#                                    #   NOTE: Some mobs do not support armor or holding items such as blaze
#    properties:                     #   General mob properties
#      drops:                        #
#        -                           #
#      spawn:                        #
#        enabled: false              #   Enable or disable it
#        world: "world"              #   Set in which world should the mob spawn in e.g world, world_the_nether
#        tick-interval:              #   Spawn mob in each specified tick interval range
#          min:                      #
#          max:                      #
#        spawn-amount-range:         #   How many mobs should spawn using the given range
#          min:                      #
#          max:                      #
#        max-mob: 50                 #   How many mobs should be spawned in (Note that spawnmob command bypasses the limit but
#        location:                   #   mobs spawned using spawnmob command still counts in it)
#          pos-1:                    #   Set 2 position that the mobs will spawn in. Position works similarly just like
#            x:                      #   in worldedit
#            y:                      #
#            z:                      #
#          pos-2:                    #
#            x:                      #
#            y:                      #
#            z:                      #
#
# NOTE: mobs should be placed inside the mobs key
# For more information regarding yml check https://learnxinyminutes.com/docs/yaml/
#
# # # # # # # # # # # # # # # # # # # # # # # # # # # # # # # # # # # # # # # # # # # # # # # # # # # # # # # # # # # # # # # # # # # # # # # # # # #
mobs:
  sample-mob:
    display_name: "&7&lCustom&a&lMob"
    type: "Zombie"
    stats:
      health: 20
      damage: null
      speed: null

    inventory:
      main-hand:
      left-hand:
      head:
        LEATHER_HELMET: "{display:{color:3949738}}"
      body:
        LEATHER_CHESTPLATE: "{display:{color:3949738}}"
      legs:
        LEATHER_LEGGINGS: "{display:{color:3949738}}"
      foot:
        LEATHER_BOOTS: "{display:{color:3949738}}"

    properties:
      drops:
        ANVIL:
          meta: "{}"
          chance: 1
      spawn:
        enabled: false
        world: "world"
        tick-interval:
          min:
          max:
        spawn-amount-range:
          min: 2
          max: 5
        max-mob: 50
        location:
          pos-1:
            x:
            y:
            z:
          pos-2:
            x:
            y:
            z: